"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Bot, Check, Cloud, Code2, ExternalLink, Menu, Palette, Play, Quote, Sparkles, Star, X, Zap } from "lucide-react";
import ContactSection from "@/components/ContactSection";

const techStack = ["React", "Next.js", "Python", "AWS", "Flutter", "PostgreSQL", "TypeScript", "OpenAI"];
const services = [
  { icon: Code2, title: "Custom Software Development", description: "Web and mobile applications designed, built, and deployed to meet your business goals.", deliverables: ["Websites and business applications", "Mobile products from one shared codebase", "APIs, integrations, and deployment"], tags: ["React", "Next.js", "Flutter"], engagement: "Fixed or retainer" },
  { icon: Cloud, title: "Technical Consulting", description: "Strategic guidance on architecture, technology selection, scalability, and product planning.", deliverables: ["Architecture and technology reviews", "Scalability and roadmap planning", "Practical technical direction"], tags: ["AWS", "Node.js", "PostgreSQL"], engagement: "Fixed scope" },
  { icon: Palette, title: "UI/UX Design", description: "Modern, intuitive interfaces designed to improve user experience and engagement.", deliverables: ["User flows and wireframes", "High-fidelity product interfaces", "Design systems and prototypes"], tags: ["Figma", "Research", "Design systems"], engagement: "Fixed scope" },
  { icon: Bot, title: "Quality Assurance", description: "Comprehensive testing and quality checks to ensure reliability, performance, and stability.", deliverables: ["Functional and regression testing", "Performance and accessibility checks", "Release confidence and documentation"], tags: ["QA", "Automation", "CI/CD"], engagement: "Fixed or retainer" },
];
const processSteps = [
  ["01", "Tell us what you need", "Start with a call", "A short call or message is enough to understand what you are building and where you need help."],
  ["02", "Get a clear proposal", "Scope and price", "We share the scope, timeline, and price in plain language, within a short period of time."],
  ["03", "We build, you stay in the loop", "Regular updates", "Shared dashboards and regular updates keep your team close to the work at every stage."],
  ["04", "Ship and support", "Ongoing support", "We do not disappear after launch. Ongoing product support is always available."],
];
const caseStudies = [
  { industry: "Fintech", title: "A faster path through onboarding", problem: "A regulated lender was losing qualified applicants during a fragmented KYC flow.", stack: ["Next.js", "AWS", "Python"], outcome: "42% higher completion", detail: "and 2.1x faster verification" },
  { industry: "Logistics", title: "Dispatch without the spreadsheet", problem: "A regional operator needed one source of truth for drivers, routes, and live exceptions.", stack: ["Flutter", "Node.js", "PostgreSQL"], outcome: "50k DAU supported", detail: "with 3.5 hours saved per dispatcher" },
  { industry: "B2B SaaS", title: "Infrastructure ready for demand", problem: "A growing SaaS product faced rising cloud spend and outages during every traffic spike.", stack: ["AWS", "Kubernetes", "Terraform"], outcome: "38% lower cloud spend", detail: "with zero-downtime failover" },
];
const testimonials = [
  { quote: "They shipped in three weeks what our previous agency quoted six months for. The senior-only staffing claim actually held up.", name: "Sarah Whitfield", role: "CTO, Fintech startup", initials: "SW" },
  { quote: "The weekly demos made our distributed team feel like one team. We always knew what was happening and why.", name: "Marcus Chen", role: "VP Engineering, Northstar", initials: "MC" },
  { quote: "Our AWS bill dropped 38% in the first month after their infrastructure review. The engagement paid for itself.", name: "Priya Nair", role: "Head of Product, Relay", initials: "PN" },
];
const plans = [
  { title: "Dedicated team", type: "Retainer", price: "From $8k/mo", description: "A stable senior team embedded in your roadmap.", features: ["Weekly planning and demos", "Flexible team size", "Continuous product ownership"] },
  { title: "Fixed-scope project", type: "Best for defined outcomes", price: "From $5k", description: "A clear deliverable, timeline, and price from day one.", features: ["Defined scope and milestones", "Weekly progress reporting", "90-day post-launch warranty"], featured: true },
  { title: "Staff augmentation", type: "Flexible capacity", price: "From $3.5k/mo", description: "Senior specialists who plug directly into your existing team.", features: ["Vetted senior engineers", "Month-to-month flexibility", "Your tools, rituals, and process"] },
];
const reveal = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55 } } };

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeStep, setActiveStep] = useState(0);
  const [activePlan, setActivePlan] = useState(1);
  return (
    <main className="saas-site">
      <header className="saas-header"><a href="#top" className="saas-logo"><span><Sparkles size={15} /></span>Nepal Exporting IT</a><nav className={`saas-nav ${menuOpen ? "is-open" : ""}`} aria-label="Main navigation"><a href="#services" onClick={() => setMenuOpen(false)}>Services</a><a href="#process" onClick={() => setMenuOpen(false)}>How we work</a><a href="#about" onClick={() => setMenuOpen(false)}>Why us</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></nav><a href="#contact" className="saas-header-cta">Get a free quote <ArrowRight size={15} /></a><button className="menu-trigger" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-controls="main-navigation" aria-label={menuOpen ? "Close menu" : "Open menu"}>{menuOpen ? <X /> : <Menu />}</button></header>
      <section id="top" className="saas-hero"><div className="hero-glow" /><motion.div initial="hidden" animate="visible" variants={reveal} className="hero-copy"><div className="saas-badge"><span className="pulse-dot" />IT outsourcing <b>·</b> Kathmandu, Nepal</div><h1>Reliable tech for<br /><span>growing businesses.</span></h1><p className="hero-subtitle">We design, build, and support digital products for companies worldwide, with clear communication from the first conversation to launch.</p><div className="hero-ctas"><a href="#contact" className="saas-button primary">Tell us what you need <ArrowRight size={17} /></a><a href="#services" className="saas-button secondary"><Play size={15} /> Explore services</a></div><div className="hero-trust"><span>Simple process</span><strong>CLEAR SCOPE</strong><strong>WEEKLY UPDATES</strong><strong>ONGOING SUPPORT</strong></div></motion.div><div className="hero-terminal"><div className="terminal-top"><span /><span /><span /><label>nepal exporting it / delivery</label></div><div className="terminal-body"><p><i>$</i> nepal-exporting-it start --together</p><p className="terminal-muted">Making your next idea easier to deliver...</p><p><b className="terminal-green">✓</b> Clear scope and proposal</p><p><b className="terminal-green">✓</b> One team, one point of contact</p><p><b className="terminal-green">✓</b> Support after launch</p><div className="terminal-line"><span>communication</span><div><b /><b /><b /><b /><b /><b /><b /></div><span>clear</span></div></div></div></section>
      <div className="tech-ribbon"><div className="tech-track">{[...techStack, ...techStack].map((tech, index) => <span key={`${tech}-${index}`}><Zap size={13} />{tech}</span>)}</div></div>
      <motion.section className="metric-strip" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .25 }} variants={reveal}>{[["01", "One accountable team"], ["02", "Clear weekly updates"], ["03", "Flexible project scope"], ["04", "Support after launch"]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</motion.section>
      <motion.section id="services" className="dark-section services-section" initial="hidden" whileInView="visible" viewport={{ once: true, amount: .1 }} variants={reveal}><div className="section-kicker">WHAT WE DO <span>01 — 04</span></div><div className="section-intro"><h2>Engineering that<br /><em>moves the needle.</em></h2><p>From first sketch to production systems, we bring the right senior people and a pragmatic process to every engagement.</p></div><div className="services-matrix">{services.map(({ icon: Icon, ...service }) => <article className="service-item" key={service.title}><div className="service-icon"><Icon size={21} /></div><div><h3>{service.title}</h3><p>{service.description}</p><ul>{service.deliverables.map((deliverable) => <li key={deliverable}><Check size={14} />{deliverable}</li>)}</ul><div className="service-foot"><div>{service.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><small>{service.engagement}</small></div></div></article>)}</div></motion.section>
      <section id="process" className="process-section"><div className="section-kicker">HOW WE WORK <span>PROCESS</span></div><div className="section-intro"><h2>A clear path from<br /><em>idea to impact.</em></h2><p>No black boxes. No handoff gaps. You always know what is happening and what comes next.</p></div><div className="timeline"><div className="timeline-line"><span style={{ width: `${(activeStep + 1) * 25}%` }} /></div>{processSteps.map(([number, title, timing, text], index) => <button className={`timeline-step ${index === activeStep ? "active" : ""}`} key={number} onClick={() => setActiveStep(index)}><span className="timeline-number">{number}</span><span className="timeline-title">{title}</span><span className="timeline-timing">{timing}</span>{index === activeStep && <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }}>{text}</motion.p>}</button>)}</div></section>
      <section id="work" className="dark-section work-section"><div className="section-kicker">SELECTED WORK <a href="#contact">View all case studies <ExternalLink size={13} /></a></div><div className="section-intro"><h2>Proof, not<br /><em>promises.</em></h2><p>Real products. Real constraints. Measurable outcomes for teams that needed momentum.</p></div><div className="case-grid">{caseStudies.map((item, index) => <article className="case-card" key={item.title}><div className={`case-visual case-visual-${index}`}><span>{item.industry}</span><div className="case-orbit" /><div className="case-graph"><b /><b /><b /><b /><b /></div></div><div className="case-content"><span className="case-industry">{item.industry}</span><h3>{item.title}</h3><p>{item.problem}</p><div className="case-stack">{item.stack.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="case-result"><strong>{item.outcome}</strong><span>{item.detail}</span></div></div></article>)}</div></section>
      <section id="about" className="proof-section"><div className="section-kicker">CLIENTS SAY <span>03 STORIES</span></div><div className="section-intro"><h2>Good work gets<br /><em>talked about.</em></h2></div><div className="testimonial-grid">{testimonials.map((testimonial) => <figure key={testimonial.name}><Quote size={24} className="quote-mark" /><div className="stars">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={14} fill="currentColor" />)}</div><blockquote>“{testimonial.quote}”</blockquote><figcaption><span className="avatar">{testimonial.initials}</span><span><strong>{testimonial.name}</strong><small>{testimonial.role}</small></span></figcaption></figure>)}</div></section>
      <section id="pricing" className="pricing-section"><div className="section-kicker">ENGAGEMENT MODELS <span>FLEXIBLE BY DESIGN</span></div><div className="section-intro"><h2>Choose your<br /><em>way to grow.</em></h2><p>Start with what you need today. We can scale the team, scope, or pace as your business changes.</p></div><div className="pricing-grid">{plans.map((plan, index) => <button key={plan.title} className={`pricing-card ${index === activePlan ? "selected" : ""}`} onClick={() => setActivePlan(index)}><div className="pricing-card-top"><span>{plan.type}</span>{plan.featured && <b>Most popular</b>}</div><h3>{plan.title}</h3><p>{plan.description}</p><strong>{plan.price}</strong><ul>{plan.features.map((feature) => <li key={feature}><Check size={14} />{feature}</li>)}</ul><span className="pricing-link">Discuss this model <ArrowRight size={15} /></span></button>)}</div></section>
      <ContactSection />
      <footer className="saas-footer"><div className="footer-brand"><a href="#top" className="saas-logo"><span><Sparkles size={15} /></span>Nepal Exporting IT</a><p>Crafting digital experiences that bridge Nepal's tech talent with global opportunities. We build, innovate, and export excellence.</p><a href="mailto:nepalexportingit2082@gmail.com">nepalexportingit2082@gmail.com</a><a href="tel:+9779823687080">+977-9823-687080 (Mexico)</a><a href="tel:+9779741812578">+977-9741-812578 (Nepal)</a><span>IT Outsourcing · Kathmandu, Nepal</span></div><div className="footer-links"><div><b>Company</b><a href="#about">About Us</a><a href="#services">Services</a><a href="#contact">Contact</a></div><div><b>Services</b><a href="#services">Website Development</a><a href="#services">Website Maintenance</a><a href="#services">Mobile App Development</a><a href="#services">Video Editing</a><a href="#services">Graphic Design</a><a href="#services">Digital Marketing</a></div><div><b>Connect</b><a href="https://www.instagram.com/nepalexportingit/" target="_blank" rel="noreferrer">Instagram</a><a href="https://linkedin.com/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://facebook.com/" target="_blank" rel="noreferrer">Facebook</a><a href="https://github.com/orgs/NepalExportingIT" target="_blank" rel="noreferrer">GitHub</a></div><div><b>Legal</b><a href="#top">Privacy Policy</a><a href="#top">Terms & Conditions</a></div></div><div className="footer-bottom">© 2026 Nepal Exporting IT. All rights reserved.<span>Made in Kathmandu</span></div></footer>
    </main>
  );
}